version: '3.1'
services:

  postgres:
    container_name: postgres-container
    image: postgres:11
    ports:
      - 5432:5432
    restart: always
   
    environment:
      POSTGRES_USER: gandalf
      POSTGRES_PASSWORD: secre7
      POSTGRES_DB: docaut_db
      
    volumes:
     - ./init:/docker-entrypoint-initdb.d/
     - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
      external: true