version: '3.1'
services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-container
    
    environment:
      MONGO_INITDB_DATABASE: gendoc_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: meerkat125
      
    ports:
      - 27017:27017
      
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js