version: '3.1'
services:

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
      
    restart: always
    
    container_name: postgres-container
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: postgres
      
    volumes:
     - postgres-data:/var/lib/postgresql/data
   
volumes:
    postgres-data:
      external: true